[package]
name = "blog_codes"
version = "0.1.0"
# edition = "2024"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_derive = "1.0.219"
serde_yaml = "0.9.34"
